spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  wechat:
    mpAppId: wxd898fcb01713c658
    mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
#    mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
    openAppId: wx6ad144e54af67d87
    openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
    mchId: 1483469312
    mchKey: 06C56A89949D617xxxxxxxxxxx
    keyPath: /var/weixin_cert/h5.p12
    notifyUrl: http://sell.natapp4.cc/sell/pay/notify
    templateId:
      orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
server:
  context-path: /sell

